name: providermodule
description: Handle every global class for kitchely chef
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  cached_network_image: ^2.3.2+1
  photo_view: ^0.10.2
  native_video_view: ^0.3.0
  flutter_vector_icons: ^0.2.1
  flutter_flexible_toast: ^0.1.4
  provider: ^4.3.2+2
  octo_image: ^0.3.0
  request:
    path: C:/pubs/request
 # reworkutils:
    #path: C:/pubs/rework_utils

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

